export class staff{


  academic:any[]=[
    //{name:"Rev. Prof. Juvenalis Asantemungu", rank:"Associate Profesor",image:"../../../../assets/staff/asantemungu.jpg", qualification:"PhD (Business Admin., Managt & Leadership): Marquette University (USA), MBA: Marquette University (USA), BBA: St. Augustine University of Tanzania",department:"BACHELOR OF BUSINESS ADMINISTRATION (BBA)",cv:""},
    {name:"Sr.Dr. Sophia Mbihije", rank:"Lecturer",image:"../../../../assets/staff/mbihije.jpg", qualification:"PhD (Education in Curriculum & Instruction): Loyola University, Chicago (USA), MSc (Analytical Chemistry): Loyola University, Chicago (USA), BSc (Chemistry): Madonna University, Michigan (USA)",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)",cv:"../../../../assets/files/sophia_mbihije_cv.pdf",},
    {name:"Rev. Dr. Apolinary K. Ndasi", rank:"Lecturer",image:"../../../../assets/staff/kaswala.jpg", qualification:"PhD (Educational Administration & Planning): Mwenge Catholic University, Master of Educational Administration: Catholic Universty (CUEA), PGDE: Catholic Universty (CUEA), Bachelor of Sacred Theology: Pontfical Urbanian University (Italy)",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)",cv:""},
    //{name:"Sr. Dr. Adolphina Mwesiga", rank:"Lecturer",image:"../../../../assets/staff/mwesiga.jpeg", qualification:"PhD (Educational Administration & Planning): Mwenge Catholic University, MED (Management and Planning): St Augustine University of Tanzania, BA (Education): St. Augustine University of Tanzania",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)",cv:""},
    {name:"Dr. Daniel Dogbe", rank:"Lecturer",image:"../../../../assets/staff/default.gif", qualification:"PhD (Special Education):Ball State University, MPhil (Special Needs - VI):University of Cape Coast, BED (Special Needs):University of Education, Winnebea,Ghana, ",cv:""},
    {name:"Dr Samuel Amoako", rank:"Lecturer",image:"../../../../assets/staff/default.gif", qualification:"PhD (Special Education):University of Education, Winnebea,Ghana, MED (Special Education Needs:The University of Leeds, Master (Hearing Impairment):The University of Manchester, Diploma (Special Education):University of Cape Coast ",cv:""},
    {name:"Dr Ephraim Kalanje", rank:"Lecturer",image:"../../../../assets/staff/default.gif", qualification:"PhD (Philosophy):Abo Akademi University, MED (Special Education Needs):Abo Akademi University, BED (Special Needs):Abo Akademi University ",cv:""},
    {name:"Dr. Eugen Philip", rank:"Lecturer",image:"../../../../assets/staff/eugen.jpg", qualification:"PhD Philosophy: Univesrity of Dodoma, MED (Open & Distance Learning): Open University of Tanzania, Bachelor of Education: University of Dar es Salaam",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)",cv:""},
    {name:"Dr. Ildephonce Mkama", rank:"Senior Lecturer",image:"../../../../assets/staff/mkama.jpeg", qualification:"PhD Philosophy: University of the Witwatersrand, MA (Linguistics): St. Augustine University of Tanzania, BA (Education): St. Augustine University of Tanzania",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)", branch:"ENGLISH/ LINGUISTICS/ LITERATURE",cv:""},
    {name:"Dr. Julius Nyaombo", rank:"Lecturer",image:"../../../../assets/staff/nyaombo.jpg", qualification:"PhD (Natural Resource Assesment& Management):University of Dar es Salaam, MSc (Natural Resources Assessment & Management): University of Dar es Salaam, BAED (Geography): University of Dar es Salaam",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)GRAPHY", branch:"GEOGRAPHY",cv:""},
    {name:"Dr. Luther I. Kawiche", rank:"Lecturer",image:"../../../../assets/staff/kawiche.jpg", qualification:"PhD (Demography): University of Dar es Salaam, MA (Demography): University of Dar es Salaam, BA (Geography & Environmental  Studies): University of Dar es Salaam",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)", branch:"GEOGRAPHY",cv:""},
    {name:"Dr. Alfred Ong'ang'a", rank:"Lecturer",image:"../../../../assets/staff/alfred.jpg", qualification:"PhD (Literature): Kenyatta University, MA (Literature): Kenyatta University (Kenya), BA (Education): Kenyatta University (Kenya) ",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)", branch:"ENGLISH/ LINGUISTICS/ LITERATURE",cv:""},
    {name:"Grace Mkosamali", rank:"Assistant Lecturer",image:"../../../../assets/staff/mkosamali.jpeg", qualification:"MA (Counselling Psychology: Bishop Magambo Counsellor Training Institute (Uganda), Bachelor in Counselling Psychology (Uganda): University of Kisubi (Uganda)",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)",cv:""},
    {name:"Koboli Milobo", rank:"Assistant Lecturer",image:"../../../../assets/staff/koboli.jpg", qualification:"MED (Management & Planning): Stella Maris University College, BA (Education): St Augustine University of Tanzania",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)",cv:""},
    {name:"Renata C. Nyelo", rank:"Assistant Lecturer",image:"../../../../assets/staff/nyero.jpg", qualification:"MED (Administration & Planning): Catholic University of Eatern Africa (Kenya), BED (Geography & History): Catholic University of Eatern Africa (Kenya)",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)",cv:""},
    
    {name:"Anna Ahmed", rank:"Assistant Lecturer",image:"../../../../assets/staff/anna.jpg", qualification:"Master of Geography & Environmental Management: University of Dar es Salaam, BA (Education): University of Dar es Salaam",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)", branch:"GEOGRAPHY",cv:""},
    
    {name:"Einhard Mgaya", rank:"Assistant Lecturer",image:"../../../../assets/staff/default.gif", qualification:"MA (History): St. Augustine University of Tanzania, Bachelor of Education: Catholic University of Eatern Africa (Kenya)",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)", branch:"HISTORY",cv:""},
    {name:"Clavery Kayugumi", rank:"Assistant Lecturer",image:"../../../../assets/staff/kayugumi.jpg", qualification:"MA (History): St. Augustine University of Tanzania, BA (Education): St. Augustine University of Tanzania",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)", branch:"HISTORY",cv:""},
    //{name:"Manka S. Mtoi", rank:"Assistant Lecturer",image:"../../../../assets/staff/default.gif", qualification:"MA (History):St. Augustine University of Tanzania, BA (Education - History): St. Augustine University of Tanzania",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)", branch:"HISTORY",cv:""},
    //{name:"Francis Daudi", rank:"Assistant Lecturer",image:"../../../../assets/staff/default.gif", qualification:"MA (History): Bangalore University (India), BA (Education - History): St Augustine University of Tanzania",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)", branch:"HISTORY",cv:""},
    //{name:"Prof. Henry R.T. Muzale", rank:"Associate Professor",image:"../../../../assets/staff/default.gif", qualification:"PhD (Linguistics): Memorial University of Newfoundland (Canada), MA (Linguistics): University of Dar es Salaam, BA (Education): University of Dar es Salaam",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)", branch:"ENGLISH/ LINGUISTICS/ LITERATURE",cv:""},
    {name:"Triphonius Lissu", rank:"Assistant Lecturer",image:"../../../../assets/staff/lissu.jpg", qualification:"MA (Linguistics): St. Augustine University of Tanzania, BA (Education): St. Augustine University of Tanzania",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)", branch:"ENGLISH/ LINGUISTICS/ LITERATURE",cv:""},
    
    {name:"Rainer Likongo", rank:"Assistant Lecturer",image:"../../../../assets/staff/likongo.jpg", qualification:"MA (Linguistics): St. Augustine University of Tanzania, BA (Education): St. Augustine University of Tanzania",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)", branch:"ENGLISH/ LINGUISTICS/ LITERATURE",cv:""},
    
    {name:"Gwakisa Kaswaga", rank:"Assistant Lecturer",image:"../../../../assets/staff/kaswaga.jpg", qualification:"MA (Literature): University of Dar es Salaam, Bachelor of Education: Teofili Kisanji University",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)", branch:"ENGLISH/ LINGUISTICS/ LITERATURE",cv:""},
    {name:"Andrew Kifua", rank:"Assistant Lecturer",image:"../../../../assets/staff/default.gif", qualification:"MBA: St. Augustine University of Tanzania, BBA (Accounts): St. Augustine University of Tanzania",cv:""},
    //{name:"Elihaki Yonazi", rank:"Assistant Lecturer",image:"../../../../assets/staff/elihaki.jpg", qualification:"MA (Kiswahili - Isimu/Fasihi): University of Dar es Salaam, BA (Education): University of Dar es Salaam",department:"BACHELOR OF ARTS WITH EDUCATION (BAED)", branch:"KISWAHILI",cv:""},

    {name:"Harriet Malichi", rank:"Assistant Lecturer",image:"../../../../assets/staff/default.gif", qualification:"MED (Special Education): University of Zambia, BED (Special Needs): University of Zambia",department:"BACHELOR OF SPECIAL NEEDS EDUCATION (BEDSN)",cv:""},
    {name:"Fraterinus O. Mutatembwa", rank:"Assistant Lecturer",image:"../../../../assets/staff/osward.jpg", qualification:"MED (Special Education - HI): Sebastian Kolowa Memorial University, BED (Special Needs): Sebastian Kolowa Memorial University",department:"BACHELOR OF SPECIAL NEEDS EDUCATION (BEDSN)",cv:""},
    {name:"Gideon D. Kaziri", rank:"Assistant Lecturer",image:"../../../../assets/staff/gideon.jpeg", qualification:"MED (Special Education - HI): Sebastian Kolowa Memorial University, BED (Special Needs): Sebastian Kolowa Memorial University",department:"BACHELOR OF SPECIAL NEEDS EDUCATION (BEDSN)",cv:""},
    //{name:"Dr Mary Runo", rank:"Senior Lecturer",image:"../../../../assets/staff/default.gif", qualification:"PhD (Special Needs): Kenyatta University, MED (Special Needs): Jersey City State Collage, BED (Special Needs): Jersey City State Collage",department:"BACHELOR OF SPECIAL NEEDS EDUCATION (BEDSN)",cv:""},
    {name:"Elijah Kokse", rank:"Assistant Lecturer",image:"../../../../assets/staff/koske.jpg", qualification:"MED (Special Needs): Brunel University, BED (Special Needs):Kenyatta University",department:"BACHELOR OF SPECIAL NEEDS EDUCATION (BEDSN)",cv:""},
    
    {name:"Filbert Zomba", rank:"Assistant Lecturer",image:"../../../../assets/staff/zomba.jpg", qualification:"MBA: St. Augustine University of Tanzania, Advanced Diploma (Accountancy): St. Augustine University of Tanzania",department:"BACHELOR OF BUSINESS ADMINISTRATION (BBA)",cv:""},
    {name:"Placid Komba", rank:"Assistant Lecturer",image:"../../../../assets/staff/komba.jpg", qualification:"Master of Business Management: Moshi Cooperative University, BA (Marketing & Entrepreneurship): Moshi Cooperative University",department:"BACHELOR OF BUSINESS ADMINISTRATION (BBA)",cv:""},
    {name:"Patrick Chekwe", rank:"Assistant Lecturer",image:"../../../../assets/staff/default.gif", qualification:"MA GEM: University of Dar es Salaam, BA GEN: University of Dar es Salaam",cv:""},
    //{name:"Josina Mshana", rank:"Assistant Lecturer",image:"../../../../assets/staff/mshana.jpg", qualification:"Master of Business Management: Moshi Cooperative University, BBA: St. Augustine University of Tanzania",department:"BACHELOR OF BUSINESS ADMINISTRATION (BBA)",cv:""},
    {name:"Saikon J. Nokoren", rank:"Assistant Lecturer",image:"../../../../assets/staff/justin.jpeg", qualification:"Postgraduate Diploma in Legal Practice (PDLP): The Law  School of Tanzania, LLM: Ruaha Catholic University, LLB: Tumaini University",department:"BACHELOR OF BUSINESS ADMINISTRATION (BBA)",cv:""},
    {name:"Faustine Rwechungura", rank:"Assistant Lecturer",image:"../../../../assets/staff/default.gif", qualification:"Master of Theology: Radboud University (Netherland), Bachelor of Theology: Catholic University of Eatern Africa (Kenya)",department:"BACHELOR OF BUSINESS ADMINISTRATION (BBA)",cv:""},
    {name:"Edgar Pastory", rank:"Assistant Lecturer",image:"../../../../assets/staff/mushumbushi.jpg", qualification:"Master of Arts in Sociology: St Augustine University of Tanzania, Bachelor of Arts in Sociology: St Augustine University of Tanzania",department:"BACHELOR OF BUSINESS ADMINISTRATION (BBA)",cv:""},
    {name:"Upendo Ulaya", rank:"Assistant Lecturer",image:"../../../../assets/staff/default.gif", qualification:"MA (History): Gotland University, BAED:St. Augustine University of Tanzania",cv:""},
    //{name:"Phides Kagwa", rank:"Assistant Lecturer",image:"../../../../assets/staff/default.gif", qualification:"MA (Kiswahili - Isimui): University of Dar es Salaam, BA (Kiswahili):University of Dar es Salaam",cv:""},
    {name:"Shukuru Mukama", rank:"Assistant Lecturer",image:"../../../../assets/staff/default.gif", qualification:"MA (Kiswahili - Fasihi): University of Dar es Salaam, BA (Education):Opean University",cv:""},
    {name:"Denice Salapion", rank:"Assistant Lecturer",image:"../../../../assets/staff/default.gif", qualification:"MA (Kiswahili - Isimui): University of Dar es Salaam, BA (Education):St. Augustine University of Tanzania",cv:""},
    {name:"Msei Nyagani", rank:"Assistant Lecturer",image:"../../../../assets/staff/default.gif", qualification:"MA (Linguistics): St. Augustine University of Tanzania, BAED:Muslim University of Mororgoro",cv:""},
    {name:"Karuta Musa", rank:"Tutorial Assistant",image:"../../../../assets/staff/default.gif", qualification:"BED (Early Childhood): University of Dodoma",cv:""},
    //{name:"Athuman Mohamed", rank:"Tutorial Assistant", image:"../../../../assets/staff/default.gif",qualification:"BED (Special Needs): Archbishop Mihayo College of Tabora",department:"BACHELOR OF SPECIAL NEEDS EDUCATION (BEDSN)",cv:""},
    {name:"Gaga Nidwa", rank:"Tutorial Assistant",image:"../../../../assets/staff/default.gif", qualification:"BED (Special Needs): Archbishop Mihayo College of Tabora",department:"BACHELOR OF SPECIAL NEEDS EDUCATION (BEDSN)",cv:""},
    {name:"Cronel Diogenes", rank:"Tutorial Assistant",image:"../../../../assets/staff/default.gif", qualification:"BED (Special Needs): Archbishop Mihayo College of Tabora",department:"BACHELOR OF SPECIAL NEEDS EDUCATION (BEDSN)",cv:""},
    {name:"Sr Martha Herman", rank:"Tutorial Assistant",image:"../../../../assets/staff/default.gif", qualification:"BED (Special Needs): Archbishop Mihayo College of Tabora",department:"BACHELOR OF SPECIAL NEEDS EDUCATION (BEDSN)",cv:""},
    {name:"Jackson Manase", rank:"Assistant Lecturer", image:"../../../../assets/staff/default.gif",qualification:"MED (Special Education): The University of Zambia, BED (Special Needs): Archbishop Mihayo College of Tabora",department:"BACHELOR OF SPECIAL NEEDS EDUCATION (BEDSN)",cv:""},
    {name:"Magreth Nkuba", rank:"Assistant Lecturer",image:"../../../../assets/staff/default.gif", qualification:"MED (Special Education): The University of Zambia, BED (Special Needs): Archbishop Mihayo College of Tabora",department:"BACHELOR OF SPECIAL NEEDS EDUCATION (BEDSN)",cv:""},
    {name:"Ansila Nyaki", rank:"Assistant Lecturer", image:"../../../../assets/staff/default.gif",qualification:"MED (Special Education): The University of Zambia, BED (Special Needs): Archbishop Mihayo College of Tabora",department:"BACHELOR OF SPECIAL NEEDS EDUCATION (BEDSN)",cv:""},
    {name:"Nasfath Rugimbana", rank:"Tutorial Assistant",image:"../../../../assets/staff/nsfat.jpg",qualification:"Bachelor of Early Childhood Education: University of Dar- es Salaam",department:"BACHELOR OF SPECIAL NEEDS EDUCATION (BEDSN)",cv:""},
  ]

  hod:any[]=[
    {image:"../../../../assets/staff/koboli.jpg", name:"Koboli Milobo", dep:"Quality Assurance", qualification:"MED (Management & Planning): Stella Maris University College, BA (Education): St Augustine University of Tanzania"},
    {image:"../../../../assets/staff/mkama.jpeg", name:"Dr. Ildephonce Mkama", dep:"Dean of Faculty of Education and Social Sciences", qualification:"PhD Philosophy: University of the Witwatersrand, MA (Linguistics): St. Augustine University of Tanzania, BA (Education): St. Augustine University of Tanzania"},
    {image:"../../../../assets/staff/kaswala.jpg", name:"Rev. Dr. Apolinary K. Ndasi", dep:"Director of Postgraduate Studies, Research and Consultancy", qualification:"PhD (Educational Administration & Planning): Mwenge Catholic University, Master of Educational Administration: Catholic Universty (CUEA), Bachelor of Sacred Theology: Pontfical Urbanian University (Italy)"},
    {image:"../../../../assets/staff/nyaombo.jpg", name:"Dr. Julius Nyaombo", dep:"Examination Officer", qualification:"PhD in Natural Resources Assessment and Management: Univesrity of Dar es Salaam, MSc (Natural Resources Assessment and Management): Univesrity of Dar es Salaam, Bachelor Arts with Education: University of Dar es Salaam"},
    {image:"../../../../assets/staff/mkosamali.jpeg", name:"Sr. Grace Mkosamali", dep:"Counseling", qualification:"MA (Counselling Psychology: Bishop Magambo Counsellor Training Institute (Uganda), Bachelor in Counselling Psychology (Uganda): University of Kisubi (Uganda)"},
    {image:"../../../../assets/staff/kawiche.jpg", name:"Dr. Luther I. Kawiche", dep:"Head of Department of Education Foundation", qualification:"PhD (Demography): University of Dar es Salaam, MA (Demography): University of Dar es Salaam, BA (Geography & Environmental  Studies): University of Dar es Salaam"},
    {image:"../../../../assets/staff/lissu.jpg", name:"Triphonius Lissu", dep:"Head of Unit of Business Administration and Social Sciences", qualification:"MA (Linguistics): St. Augustine University of Tanzania, BA (Education): St. Augustine University of Tanzania"},
    //{image:"../../../../assets/staff/mkama.jpeg", name:"Dr. Ildephonce Mkama", dep:"Head of Department of Special Needs Education", qualification:"PhD Philosophy: University of the Witwatersrand, MA (Linguistics): St. Augustine University of Tanzania, BA (Education): St. Augustine University of Tanzania"},
    {image:"../../../../assets/staff/kaswaga.jpg", name:"Gwakisa Kaswaga", dep:"Coordinator of Teaching Practice", qualification:"MA (Literature): University of Dar es Salaam, Bachelor of Education: Teofili Kisanji University"},
    {image:"../../../../assets/staff/eugen.jpg", name:"Dr. Eugen Philip", dep:"Chief Librarian", qualification:"PhD Philosophy: Univesrity of Dodoma, MED (Open & Distance Learning): Open University of Tanzania, Bachelor of Education: University of Dar es Salaam"},
    {image:"../../../../assets/staff/osward.jpg", name:"Fraterinus O. Mutatembwa", dep:"Head of Department of Special Needs Education and Coodnator of Center of Inclusive Education", qualification:"MED (Special Education - HI): Sebastian Kolowa Memorial University, BED (Special Needs): Sebastian Kolowa Memorial University"},
    //{image:"../../../../assets/staff/alfred.jpg", name:"Dr. Alfred Ong'ang'a", dep:"Head of Unit of Business Administration and Social Sciences", qualification:"PhD (Literature): Kenyatta University, MA (Literature): Kenyatta University (Kenya), BA (Education): Kenyatta University (Kenya) "},
    {image:"../../../../assets/staff/kayugumi.jpg", name:"Clavery Kayugumi", dep:"Dean of Students", qualification:"Masters in History: St Augustine University of Tanzania, Bachelor of Arts with Education: St Augustine University of Tanzania"},
    {image:"../../../../assets/staff/mande.jpg", name:"Rev. Josephat Mande", dep:"Chaplain", qualification:"MA (Sacred Theology): St.Thomas Aquinas University Rome, Diploma in Theology: St Paul Major Seminary Tabora"},
    {image:"../../../../assets/staff/mwanga.jpg", name:"Judith Mwanga", dep:"Human Resource Management Officer", qualification:"MBA ( Human Resource): Archbishop Mihayo University College of Tabora, Bsc (Tourism Management): Sokoine University of Agriculture"},
    //{image:"../../../../assets/staff/default.gif", name:"Julian Dalika", dep:"Fundraiser", qualification:""},
    {image:"../../../../assets/staff/mugo.jpg", name:"Amatyus Mugonzibwa", dep:"Loan Officer", qualification:"Bachelor of Sociology: St Augustine University of Tanzania"},
    {image:"../../../../assets/staff/kapfizi.jpg", name:"Sr. Ester Kapfizi", dep:"Admission Officer", qualification:"MEMP (Educational Management and Planning): Archbishop Mihayo University College of Tabora, BA (Education): Catholic Universty (CUEA)"},
    {image:"../../../../assets/staff/alois.jpg", name:"Alois D Kyando", dep:"IT Officer", qualification:"Bsc (Computer Science  Information System): Ruaha University Collage, Diploma in Computer Science:Ruaha University Collage"},
    {image:"../../../../assets/staff/default.gif", name:"Isaya Bruno Anyingisye", dep:"Dispensary In charge", qualification:"Advance Diploma in Clinical  Medicine: Bugando Medical Training Centre, Diploma in Clinical Medicine: Songea Medical Training Centre"},
    {image:"../../../../assets/staff/nimilwa.jpg", name:"Paschal Charles", dep:"Public Relation Officer", qualification:"Bachelor of Public Relation and Marketing: St Augustine University of Tanzania"},
    {image:"../../../../assets/staff/justin.jpeg", name:"Saikon J. Nokoren", dep:"Legal Officer", qualification:"Postgraduate Diploma in Legal Practice (PDLP): The Law  School of Tanzania, LLM: Ruaha Catholic University, LLB: Tumaini University"},

  ]
  administrative:any[]=[
    {name:"Rev.Josephat Mande",title:"Chaplain",image:"../../../../assets/staff/mande.jpg",desc:"MA (Sacred Theology): St.Thomas Aquinas University Rome, Diploma in Theology: St Paul Major Seminary Tabora"},
    {name:"Judith Mwanga",title:"Human Resources Management Officer",image:"../../../../assets/staff/mwanga.jpg",desc:"MBA ( Human Resource): Archbishop Mihayo University College of Tabora, Bsc (Tourism Management): Sokoine University of Agriculture"},
    {name:"Pascalina Joseph",title:"Assistant Accountant",image:"../../../../assets/staff/paskalina.jpeg",desc:"MBA: Archbishop Mihayo University College of Tabora, Advance Diploma in Accounty: St Augustine University of Tanzania"},
    {name:"Isaya Bruno Anyingisye",title:"Clinical Officer",image:"../../../../assets/staff/default.gif",desc:"Advance Diploma in Clinical  Medicine: Bugando Medical Training Centre, Diploma in Clinical Medicine: Songea Medical Training Centre "},
    {name:"Sr Liberatus Mhema",title:"Assistant Accountant",image:"../../../../assets/staff/mhema.jpg",desc:"MBA: St Augustine University of Tanzania, BBA: St Augustine University of Tanzania"},
    {name:"Gaudensia Mtaki",title:"Cashier",image:"../../../../assets/staff/mtaki.jpeg",desc:"Certificate: National Business Examination"},
    {name:"Amatyus Mugonzibwa",title:"Loan Officer",image:"../../../../assets/staff/mugo.jpg",desc:"Bachelor of Sociology: St Augustine University of Tanzania"},
    {name:"Sr Ester Kapfizi",title:"Admission Officer",image:"../../../../assets/staff/kapfizi.jpg",desc:"MEMP (Educational Management and Planning): Archbishop Mihayo University College of Tabora, BA (Education): Catholic Universty (CUEA)"},
    {name:"Martha Lumambo",title:"Administrative Secretary",image:"../../../../assets/staff/lumambo.jpeg",desc:"Diploma: Tanzania Public Service Collage, Certificate: Tanzania Public Service Collage"},
    {name:"Alois D Kyando",title:"IT Officer",image:"../../../../assets/staff/alois.jpg",desc:"Bsc (Computer Science  Information System): Ruaha Catholic University, Diploma in Computer Science: Ruaha Catholic University"},
    {name:"Daudi Mabula",title:"Assistant IT Officer",image:"../../../../assets/staff/default.gif",desc:"Bsc (Computer Engineering): Mbeya University of Science and Technology"},
    {name:"Sr Victoria Mamiro",title:"Assistant Medical Officer",image:"../../../../assets/staff/default.gif",desc:"Advance Diploma in Clinical  Medicine: Bugando Medical Training Centre, Diploma in Clinical Medicine: Songea Medical Training Centre"},
    {name:"John Lukonge",title:"Technical Assistant",image:"../../../../assets/staff/lukonge.jpg",desc:"BED (Special Needs): Archbishop Mihayo University College of Tabora"},
    {name:"Emmanuel Sitta",title:"Technical Assistant",image:"../../../../assets/staff/sitta.jpg",desc:"BED (Special Needs): Archbishop Mihayo University College of Tabora"},
    {name:"Erick Massamaki",title:"Eletrician",image:"../../../../assets/staff/masamaki.jpg",desc:"Certificate: VETA"},
    {name:"Elizabeth Sospeter",title:"Librarian",image:"../../../../assets/staff/mlona.jpg",desc:"Bsc Library and Information Management: Mzumbe University, Diploma (Librarian and Records): Archbishop Mihayo University College of Tabora, Certificate (Librarian and Records): Archbishop Mihayo University College of Tabora "},
    {name:"Naisiriri Memruth",title:"Nurse",image:"../../../../assets/staff/niceriri.jpg",desc:"Certificate in Nursing: Regional Government Hospital-Tabora"},
    {name:"Julian Romanus Dalika",title:"Fundraiser",image:"../../../../assets/staff/default.gif",desc:"Advanced Diploma in Community Development: Community Development Traning Institute-TENGERU"},
    {name:"Justina Marwa",title:"Estate Manager",image:"../../../../assets/staff/default.gif",desc:"Advanced Diploma in Jounalism: St Augustine University of Tanzania, MA (Socilogy): St Augustine University of Tanzania"},
    {name:"Emmanuel Simon",title:"Assistant Librarian",image:"../../../../assets/staff/imma.jpg",desc:"Certificate in Librarianship and Records: Archbishop Mihayo University College of Tabora"},
    {name:"Richard Ngeze",title:"Assistant Librarian",image:"../../../../assets/staff/ngeze.jpeg",desc:"Diploma in Procurement and Supply chain: Archbishop Mihayo University College of Tabora, Certificate in Librarianship and Records: Ruaha University Collage"},
    {name:"Walter Silayo",title:"Assistant Librarian",image:"../../../../assets/staff/silayo.jpg",desc:"Diploma in Procurement and Supply chain: Archbishop Mihayo University College of Tabora, Certificate in Librarianship and Records: Chuo cha Ukutubi na Uhifadhi"},
    {name:"Mathias Louis",title:"Assistant Estate Manager",image:"../../../../assets/staff/luis.jpg",desc:"Bachelor of Law: St Augustine University of Tanzania"},
    {name:"Paschal Charles",title:"Public Relations Officer",image:"../../../../assets/staff/nimilwa.jpg",desc:"BA (Public Relations and Marketing): St Augustine University of Tanzania"},
    {name:"Winfrida Ngoloke",title:"Laboratory",image:"../../../../assets/staff/ngoloke.jpg",desc:"Diploma (Medical Laboratory): Nkinga Institute of Health Science, Certificate (Health Laboratory): Bhakita  Health Training Institute"},
    {name:"Sr Catherine Masanibwa",title:"Nurse",image:"../../../../assets/staff/default.gif",desc:"Certificate in Health: PATH"},
    {name:"Rehema Mlimuka",title:"Nurse",image:"../../../../assets/staff/default.gif",desc:"Certificate in Nursing: Regional Government Hospital-Tabora"},
    {name:"Moses Kabeya",title:"Data Clerk",image:"../../../../assets/staff/default.gif",desc:"Certificate in Computer"},
    //{name:"Glory Kisamo",title:"Assistant Accountant",image:"../../../../assets/staff/default.gif",desc:"Diploma:Moshi Cooperative University, Certificate:Moshi Cooperative University"},
    {name:"Elia Elia",title:"Assistant Accountant",image:"../../../../assets/staff/default.gif",desc:"Diploma in Accounts:Institute of Accountancy Arusha"},

  ]

  gBoardMembers:any[]=[
    {name:"His Eminence Protase Cardinal, RUGAMBWA",title:"Chairman",desc:"Archibishop of Tabora",image:"../../../../assets/staff/default.gif"},
    {name:"Rt Rev. Mapunda, EDWARD",title:"Member",desc:"Bishop of Singida",image:"../../../../assets/staff/default.gif"},
    {name:"Amb. Prof Mahalu, COSTA RICKY",title:"Member",desc:"SAUT Vice Chancellor",image:"../../../../assets/staff/default.gif"},
    //{name:"Rev.Prof. Asantemungu, JUVENALIS",title:"Secretary",desc:"Deputy Principal for Academic Affairs",image:"../../../../assets/staff/asantemungu.jpeg"},
    {name:"Rev. Fr Kitima, CHARLES",title:"Member",desc:"TEC Secretary General",image:"../../../../assets/staff/default.gif"},
    {name:"Prof. Rugarabamu, PASCHALIS",title:"Member",desc:"V.C CUHAS",image:"../../../../assets/staff/default.gif"},
    //{name:"Prof. Amb. Costa Ricky Mahalu",title:"Member",desc:"SAUT",image:"../../../../assets/staff/default.gif"},
    {name:"Miss. Joseph, PASKALINA",title:"Member",desc:"Busar-AMUCTA",image:"../../../../assets/staff/paskalina.jpeg"},
    //{name:"Dr Mlimuka, AGGREY K",title:"Member",desc:"Higher Learning Institutions",image:"../../../../assets/staff/default.gif"},
    //{name:"Sr Dr Mbihije, SOPHIA",title:"Member",desc:" AMUCTA",image:"../../../../assets/staff/mbihije.jpg"},
    {name:"Mr. Sanga, CLEMENT",title:"Member",desc:"Representative of MoEST",image:"../../../../assets/staff/default.gif"},
    {name:"Mr Mtaki, REVOCATUS",title:"Member",desc:"Advocate",image:"../../../../assets/staff/default.gif"},
    {name:"Rev.Prof. Asantemungu, JUVENALIS",title:"Principal AMUCTA",desc:"Member",image:"../../../../assets/staff/asantemungu.jpg"},
    {name:"Rev. Prof. Emmanuel Wabanhu ,",title:"Member",desc:"Deputy Principal for Administration and Finance, AMUCTA",image:"../../../../assets/staff/wabanhu.JPG"},
    {name:"AMUCTASO President,",title:"Member",desc:"-",image:"../../../../assets/staff/default.gif"}
  ]
  acCommittee:any[]=[
    {name:"Rev.Prof. Asantemungu, JUVENALIS",title:"Chairman",desc:"Principal",image:"../../../../assets/staff/asantemungu.jpg"},
   // {name:"Rev.Prof. Asantemungu, JUVENALIS",title:"Vice Chairman",desc:"Deputy Principal for Academic Affairs",image:"../../../../assets/staff/asantemungu.jpg"},
    {name:"Dr. Kawiche, LUTHER ",title:"Lecturer",desc:"Dean of Faculty of Arts and Social Sciences",image:"../../../../assets/staff/default.gif"},
    //{name:"Rev. Dr Mhina, VINCENT",title:"Lecturer",desc:"HoD Business Administration Public Relations",image:"../../../../assets/staff/mhina.jpeg"},
    //{name:"Sr. Dr. Mwesiga, ADOLPHINA",title:"Lecturer",desc:"Dean of Faculty of Education",image:"../../../../assets/staff/mwesiga.jpeg"},
    {name:"Prof. Erasmus, KOMGISHA",title:"",desc:"SAUT Representative",image:"../../../../assets/staff/default.gif"},
    {name:"Dr. Philip, EUGEN M",title:"Assistant Lecturer",desc:"Examination Officer",image:"../../../../assets/staff/phillip.jpeg"},
    {name:"Rev. Dr. Ndasi, APOLNARY",title:"Lecturer",desc:"HoD Special Needs, Languages and Linguistics",image:"../../../../assets/staff/ndasi.jpeg"},
    {name:"Assistant Lecturer",title:"Quality Assurance Officer",desc:"",image:"../../../../assets/staff/lissu.jpeg"},
    {name:"Mr. Mshumbusi, EDGAR PASTORY",title:"",desc:"Dean of Students",image:"../../../../assets/staff/mushumbushi.jpeg"},
    {name:"Fr. Mgaya, EINHARD G",title:"Assistant Lecturer",desc:"Representative of Academic Staff",image:"../../../../assets/staff/mgaya.jpeg"},
    //{name:"Mr. Yohanis, KILAVE",title:"Assistant Lecturer",desc:"Chief Librarian",image:"../../../../assets/staff/yohanis.jpeg"},
    {name:"Sr Kapfizi, ESTHER",title:"",desc:"Admission Officer",image:"../../../../assets/staff/kapfizi.jpeg"},
    //{name:"Sr Dr Mwesiga, ADOLPHINA",title:"Lecturer",desc:"Director of Postgraduate Studies, Research and Consultancy",image:"../../../../assets/staff/mwesiga.jpeg"},
    {name:"AMUCTASO President",title:"",desc:"Students' Government",image:"../../../../assets/staff/default.gif"},
  ]


}
